name: Dev Branch Sync

on:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout fork
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches

      - name: Set up Git
        run: |
          git config user.name "l-hepper"
          git config user.email "l-hepper@outlook.com"

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/katabeth/FantasticNine.git
          git fetch upstream

      - name: Checkout Developer branch
        run: |
          git checkout Developer
          git pull origin Developer  # Ensure you're up-to-date with your fork

      - name: Merge upstream Developer into Developer
        run: |
          git fetch upstream
          git merge upstream/Developer --allow-unrelated-histories

      - name: Push changes
        run: |
          git push origin Developer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
